In [1]:
import numpy as np
import pandas as pd


In [2]:
# Carregar o dataset
df = pd.read_csv('C:/Users/Daniel/Desktop/Cálculo de Estatísticas Básicas com NumPy/AmesHousing.csv')

# Exibir as primeiras linhas do dataset
print(df.head())


   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  


In [3]:
# Converter colunas selecionadas em arrays NumPy
total_rooms = np.array(df['total_rooms'])
total_bedrooms = np.array(df['total_bedrooms'])
population = np.array(df['population'])
households = np.array(df['households'])
median_income = np.array(df['median_income'])

# Exibir os arrays criados
print("Total Rooms:", total_rooms[:5])
print("Total Bedrooms:", total_bedrooms[:5])
print("Population:", population[:5])
print("Households:", households[:5])
print("Median Income:", median_income[:5])


Total Rooms: [ 880. 7099. 1467. 1274. 1627.]
Total Bedrooms: [ 129. 1106.  190.  235.  280.]
Population: [ 322. 2401.  496.  558.  565.]
Households: [ 126. 1138.  177.  219.  259.]
Median Income: [8.3252 8.3014 7.2574 5.6431 3.8462]


In [4]:
# Calcular a soma de cada array
sum_total_rooms = np.sum(total_rooms)
sum_total_bedrooms = np.sum(total_bedrooms)
sum_population = np.sum(population)
sum_households = np.sum(households)
sum_median_income = np.sum(median_income)

# Exibir os resultados
print("Soma de Total Rooms:", sum_total_rooms)
print("Soma de Total Bedrooms:", sum_total_bedrooms)
print("Soma de Population:", sum_population)
print("Soma de Households:", sum_households)
print("Soma de Median Income:", sum_median_income)


Soma de Total Rooms: 54402150.0
Soma de Total Bedrooms: nan
Soma de Population: 29421840.0
Soma de Households: 10310499.0
Soma de Median Income: 79890.6495


In [5]:
# Verificar se há valores nan
nan_total_bedrooms = np.isnan(total_bedrooms).any()
print("Há valores nan em Total Bedrooms?", nan_total_bedrooms)


Há valores nan em Total Bedrooms? True


In [6]:
# Substituir valores nan por zero
total_bedrooms = np.nan_to_num(total_bedrooms, nan=0)


In [7]:
# Recalcular a soma
soma_total_bedrooms = np.sum(total_bedrooms)
print("Soma de Total Bedrooms após tratamento de nan:", soma_total_bedrooms)


Soma de Total Bedrooms após tratamento de nan: 10990309.0


In [8]:
# Calcular a média
media_total_rooms = np.mean(total_rooms)
media_total_bedrooms = np.mean(total_bedrooms)
media_population = np.mean(population)
media_households = np.mean(households)
media_median_income = np.mean(median_income)

print("Média de Total Rooms:", media_total_rooms)
print("Média de Total Bedrooms:", media_total_bedrooms)
print("Média de Population:", media_population)
print("Média de Households:", media_households)
print("Média de Median Income:", media_median_income)


Média de Total Rooms: 2635.7630813953488
Média de Total Bedrooms: 532.47621124031
Média de Population: 1425.4767441860465
Média de Households: 499.5396802325581
Média de Median Income: 3.8706710029069766


In [9]:
# Calcular o desvio padrão
desvio_total_rooms = np.std(total_rooms)
desvio_total_bedrooms = np.std(total_bedrooms)
desvio_population = np.std(population)
desvio_households = np.std(households)
desvio_median_income = np.std(median_income)

print("Desvio Padrão de Total Rooms:", desvio_total_rooms)
print("Desvio Padrão de Total Bedrooms:", desvio_total_bedrooms)
print("Desvio Padrão de Population:", desvio_population)
print("Desvio Padrão de Households:", desvio_households)
print("Desvio Padrão de Median Income:", desvio_median_income)


Desvio Padrão de Total Rooms: 2181.5624017359723
Desvio Padrão de Total Bedrooms: 422.6680933861143
Desvio Padrão de Population: 1132.434687757615
Desvio Padrão de Households: 382.3204908552571
Desvio Padrão de Median Income: 1.8997756945748738


In [10]:
# Criar matrizes a partir dos arrays
matriz_total_rooms = total_rooms.reshape(-1, 1)  # Matrizes coluna
matriz_total_bedrooms = total_bedrooms.reshape(-1, 1)
matriz_population = population.reshape(-1, 1)
matriz_households = households.reshape(-1, 1)
matriz_median_income = median_income.reshape(-1, 1)


In [11]:
# Multiplicação de matrizes
multiplicacao = np.dot(matriz_total_rooms, matriz_total_bedrooms.T)
print("Multiplicação de Matrizes (Total Rooms x Total Bedrooms):")
print(multiplicacao)


Multiplicação de Matrizes (Total Rooms x Total Bedrooms):
[[ 113520.  973280.  167200. ...  426800.  359920.  542080.]
 [ 915771. 7851494. 1348810. ... 3443015. 2903491. 4372984.]
 [ 189243. 1622502.  278730. ...  711495.  600003.  903672.]
 ...
 [ 290766. 2492924.  428260. ... 1093190.  921886. 1388464.]
 [ 239940. 2057160.  353400. ...  902100.  760740. 1145760.]
 [ 359265. 3080210.  529150. ... 1350725. 1139065. 1715560.]]


In [12]:
# Criar uma matriz quadrada 2x2 para inversão
matriz_quadrada = np.array([[1, 2], [3, 4]])

# Inverter a matriz
inversao = np.linalg.inv(matriz_quadrada)
print("Matriz Original:")
print(matriz_quadrada)
print("Matriz Inversa:")
print(inversao)


Matriz Original:
[[1 2]
 [3 4]]
Matriz Inversa:
[[-2.   1. ]
 [ 1.5 -0.5]]
